name: "1"

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          input: "asdwe"
          
        run: |
          wget https://github.com/Gomorroth/BuildPackageListing/releases/latest/download/BuildPackageListing
          chmod u+x BuildPackageListing
          ./BuildPackageListing
        
