name: "1"

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          wget https://github.com/Gomorroth/BuildPackageListing/releases/latest/download/BuildPackageListing
          chmod u+x BuildPackageListing
          ./BuildPackageListing

      - run: |
          ls -l
        
