name: "2"

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: gomorroth/vpm-build-repository@68a779bf6a5ddc82c75348f72a3e1ac25db8e2c9
        with:
          repo-token: ${{ github.token }}

      - run: |
          ls -l
        
