name: "2"

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: gomorroth/vpm-build-repository@v0.1
        with:
          repo-token: ${{ github.token }}

      - run: |
          ls -l
        
