name: "2"

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write


env:
  listPublishDirectory: Website
  pathToCi: ci
  

jobs:
  job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: vpm-build-repository
        uses: Gomorroth/vpm-build-repository@v1
        with:
          repo-token: ${{ github.token }}

      - run: |
          ls -l
          cat vpm.json
          cat index.json
