name: "2"

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: gomorroth/vpm-build-repository@b148b467ed1ed302dc2e0e28ce474f014dbcb7d2
        with:
          repo-token: ${{ github.token }}

      - run: |
          ls -l
        
