name: "2"

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: gomorroth/vpm-build-repository@6adf7ef565f96ca20365d4f0e7ac4d801d5c2a29
        with:
          repo-token: ${{ github.token }}
        

      - run: |
          ls -l
        
